spring.application.name=cart-service
server.port=8082

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cartdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=none

spring.kafka.bootstrap-servers=localhost:9092